import "./globals.css";
import { Manrope } from "next/font/google";

const primaryFont = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.className}`}
      >
        {children}
      </body>
    </html>
  );
}
